const PHONE_E164 = "18295733343";
const BRAND = "C&Cfragancias";

const imageMap = {
  "Paco Rabanne – 1 Million Lucky": "img/1 Million Lucky.jpg",
  "Initio – Absolute Aphrodisiac": "img/ABSOLUTE APHRODISIAC INITIO.jpg",
  "Armani – Stronger With You Absolutely": "img/ARMANI - STRONGER WITH YOU ABSOLUTELY.jpg",
  "BDK – Gris Charnel Extrait": "img/BDK GRIS CHARNEL EXTRAIT.jpg",
  "Carolina Herrera – CH": "img/CAROLINA HERRERA - CH.png",
  "Cartier – Déclaration L’Eau": "img/CARTIER - DECLARATION L'EAU.jpg",
  "Chanel – Chance": "img/CHANCE - CHANEL.png",
  "Chanel – Allure Homme": "img/CHANEL - ALLURE HOMME.jpg",
  "Chanel – Égoïste Platinum": "img/CHANEL - EGOISTE PLATINUM.jpg",
  "Creed – Green Irish Tweed": "img/CREED - GREEN IRISH TWEED.jpg",
  "Ferragamo – F": "img/F - FERRAGAMO.jpg",
  "Ferragamo – Uomo Urban Feel": "img/FERRAGAMO UOMO - URBAN FEEL.jpg",
  "FUGAZZI – Angel Dust": "img/fugazzi angel dust.jpg",
  "Gritti – Pomelo Sorrento": "img/GRITTI - POMELO SORRENTO.jpg",
  "Gucci Flora – Gorgeous Gardenia": "img/GUCCI FLORA GORGEOUS GARDENIA.jpg",
  "Initio – Musk Therapy": "img/INITIO - MUSK THERAPY.png",
  "Jean Paul Gaultier – Le Beau": "img/Jean Paul Gaultier - Le Beau.jpg",
  "Jean Paul Gaultier – Monsieur": "img/JEAN PAUL GAULTIER - MONSIEUR.jpg",
  "Le Labo – Santal 33": "img/Le labo santal 33.jpg",
  "Maison Margiela – Jazz Club": "img/MAISON MARGIELA JAZZ CLUB.jpg",
  "Montblanc – Explorer": "img/MONT BLANC - EXPLORER.jpg",
  "Montblanc – Legend": "img/MONT BLANC - LEGEND.jpg",
  "Montale – Ristretto Intense Café": "img/MONTALE RISTRETTO INTENSE CAFE.jpg",
  "Narcotica – Limonata": "img/NARCOTICA - LIMONATA.jpg",
  "Nishane – Ani": "img/NISHANE ANI.png",
  "Orto Parisi – Bergamask": "img/ORTO PARISI - BERGAMASK.jpg",
  "Paco Rabanne – Invictus Parfum": "img/PACO RABANNE - INVICTUS PARFUM.jpg",
  "Parfums de Marly – Carlisle": "img/PARFUMS DE MARLY - CARLISLE.jpg",
  "Parfums de Marly – Sedley": "img/PARFUMS DE MARLY - SEDLEY.jpg",
  "Parfums de Marly – Greenley": "img/PDM - GREENLEY.jpg",
  "Penhaligon’s – Duchess Rose": "img/PENHALIGONS - DUCHESS ROSE.png",
  "Penhaligon’s – Empressa": "img/PENHALIGONS EMPRESSA.jpg",
  "Perry Ellis – Perry Ellis": "img/PERRY ELLIS - PERRY ELLIS.jpg",
  "Polo Black": "img/POLO BLACK.jpg",
  "Polo Blue": "img/POLO BLUE.jpg",
  "Prada – Milano d’Iris": "img/PRADA MILANO D'IRIS.jpg",
  "ROOM 1015 – Wavechild": "img/room 1015 wavechild.png",
  "Sospiro – Vibrato": "img/sospiro Vibrato.png",
  "Terre d’Hermès": "img/TERRE D'HERMES.jpg",
  "Tom Ford – Ombré Leather": "img/TOM FORD - OMBRE LEATHER.jpg",
  "Une Nuit Nomade – Sugar Leather": "img/UNE NUIT NOMADE - SUGAR LEATHER.jpg",
  "Valentino – Born in Roma Coral Fantasy": "img/VALENTINO - BORN IN ROMA CORAL FANTASY.jpg",
  "Xerjoff – Tony Iommi Monkey Special": "img/XERJOFF - TONY IOMMI MONKEY SPECIAL.jpg",
  "YSL – MYSLF": "img/YSL - MYSLF.jpg",
  "YSL – Y EDT": "img/YSL - Y EDT.jpg"
};
